openapi: 3.0.0
info:
  version: 1.0.0
  title: TCS base realastate
  contact: Jeoff Beezos,
  email: Jeoff.Beezy@gmail.com
servers:
  - url: 'http://localhost:3000'
paths:
  /user:
    get:
      summary: 'Sample endpoint: Returns details about a particular user'
      operationId: listUser
      tags:
        - user
      parameters:
        - name: id
          in: query
          description: ID of the user
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        House:
          title: house
          type: string
          required:
          - id
          - location
          - name
        description: a new property on the market.
        properties:
        price: 
        type: integer
        maximum: 100000
        minimum: 5000
        example: '5000'
        size: 
           type: string
        suburb:
           type: string
        street name:
           type: string
             arrivalDate:
          type: string
          format: date-time
         order:
      title: order
      type: object
      properties:
        address:
          type: string
        orderTotal:
          type: integer
          maximum: 100000
          minimum: 1
          example: '5000'
        orderDate:
          type: string
          format: date-time
        arrivalDate:
          type: string
          format: date-time
        items:
          $ref: '#/components/schemas/items'
        orderId:
          type: integer
          maximum: 20000
          minimum: 1
          example: '1151'
      required:
        - address
        - items